language: ruby
rvm:
 - 2.3.0
script: bundle exec rspec spec
services:
  - postgresql
before_script:
  - psql -c "create role rails_app with createdb login password 'pass123';" -U postgres
  - bundle exec rake db:setup
notifications:
  email: true